spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL_DEV}
    username: ${MYSQL_USERNAME_DEV}
    password: ${MYSQL_PASSWORD_DEV}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  data:
    redis_mail:
      host: localhost
      port: 6379
      expire_minutes: 5
    redis_token:
      host: localhost
      port: 6380

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-token:
    expired-minutes: 5
  refresh-token:
    expired-minutes: 1440 # 1 day
