spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL_PROD}
    username: ${MYSQL_USERNAME_PROD}
    password: ${MYSQL_PASSWORD_PROD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
