server:
  port: 8080

spring:
  config:
    import: file:.env[.properties]
  profiles:
    default: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GOOGLE_SMTP_ACCOUNT}
    password: ${GOOGLE_SMTP_PW}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    title: 회원 가입 인증번호입니다.
    code-length: 6
