version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dev_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./mysql/db_dev/mysql/data:/var/lib/mysql

  redis_mail:
    image: redis:latest
    container_name: redis_mail_auth_dev
    ports:
      - "6379:6379"
    volumes:
      - ./redis/mail_auth_dev/data:/data
      - ./redis/mail_auth_dev/conf/redis.conf:/usr/local/conf/redis.conf
    command:
      - redis-server

  redis_token:
    image: redis:latest
    container_name: redis_token
    ports:
      - "6380:6379"
    volumes:
      - ./redis/token_dev/data:/data
      - ./redis/token_dev/conf/redis.conf:/usr/local/conf/redis.conf
    command:
      - redis-server
