version: "3"
services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: product_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      - ./mysql/db/mysql/data:/var/lib/mysql
